language: objective-c
before_install:
- (ruby --version)
- sudo chown -R travis ~/Library/RubyMotion
- mkdir -p ~/Library/RubyMotion/build
- sudo motion update --cache-version=3.1
gemfile:
- Gemfile
script:
- bundle exec rake clean:all
- bundle install
- bundle exec rake spec
